# Site settings
title: Alberta Tech Solutions
email: info@albertatechsolutions.com
description: > 
  Alberta Tech Solutions, based in Edmonton, is your go-to expert for cutting-edge residential and commercial technology services. Transform your living spaces with Smart Home Automation, Multiroom Audio, and Custom Home Theaters. Elevate your business with robust Enterprise Automation, POS Systems, and comprehensive IT solutions. Discover innovative security systems, AI integrations, and seamless network infrastructures designed to enhance productivity and security. Partner with us to revolutionize your tech experience!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.albertatechsolutions.com" # the base hostname & protocol for your site

# Social media links
social_media:
  facebook_url: "https://www.facebook.com/AlbertaTechSolutions"
  linkedin_url: "https://www.linkedin.com/company/alberta-tech-solutions"
  twitter_username: ATSAlbertaTech

# Contact information
contact_info:
  phone: "780-906-8765" # Your actual phone number
  address: "Edmonton, Alberta" # Specified address
  email: "info@albertatechsolutions.com" # Clean email format
  website: "http://www.albertatechsolutions.com" # Optional website field

google_analytics: G-HV7QGVGFWQ

# Keywords for SEO
keywords: 
  - Smart Home Automation
  - Residential Automation Services
  - Multiroom Audio Systems
  - Custom Home Theater Design
  - Home Security Systems
  - CCTV Installation in Edmonton
  - AI Integration Services
  - Managed IT Services Canada
  - Enterprise Automation Solutions
  - POS Systems for Businesses
  - Network Infrastructure Setup
  - Data Backup Solutions
  - Smart Home Technology Edmonton
  - Home Automation Consulting
  - Digital Signage Solutions
  - Access Control Systems
  - IT Support and Maintenance
  - Cloud Computing Solutions
  - Audio-Visual Installations
  - Smart Lighting Systems
  - Smart Thermostat Installation
  - Home Networking Services
  - Advanced Security Solutions
  - IoT Device Integration
  - Business IT Support Services
  - Home Theater Installation Services
  - Security Camera Systems
  - Digital Media Management
  - Remote Monitoring Solutions
  - Smart Building Technology
  - Energy Management Systems
  - Home Office Technology Solutions
  - Network Security Solutions
  - Interactive AV Solutions
  - Custom Software Development
  - Technology Consulting for Businesses
  - Smart Home System Integration
  - Home Wi-Fi Optimization
  - Professional AV Services
  - Smart Energy Solutions
  - Technology Lifecycle Management
  - Virtual IT Support
  - Home Automation Devices
  - Integrated Technology Solutions
  - IT Infrastructure Services
  - Smart Office Automation
plugins:
  - jekyll-sitemap

sitemap:
  include:
    - "*.html"  # Include HTML files in the sitemap
    - "*.xml"   # Include XML files in the sitemap

# Build settings
markdown: kramdown
