# Site settings
title: "Alberta Tech Solutions"
email: "info@albertatechsolutions.com"
description: "**Alberta Tech Solutions: Your Premier Partner for Smart Technology**

At Alberta Tech Solutions, we specialize in delivering cutting-edge technology solutions tailored to your needs. Our services include home automation for seamless living, state-of-the-art audio and video systems for immersive entertainment, and advanced CCTV installations for robust security. We also offer commercial automation to streamline your business operations and comprehensive IT support to keep your systems running smoothly. With a focus on innovation and customer satisfaction, Alberta Tech Solutions is dedicated to enhancing your home and business with reliable, high-quality technology. Discover the future of smart living and secure your peace of mind today!"
baseurl: "" 
url: "http://www.albertatechsolutions.com"

# User settings
owner: "Alberta Tech Solutions"
facebook_username: "albertatechsolutions"
twitter_username: "albertatechsolutions"
address:
    - line: "Edmonton, AB"
telephone: "780-906-8765"
copyright: "© 2024 Alberta Tech Solutions"

# API settings
google_api_key: "YOUR_GOOGLE_API_KEY" # Make sure to replace with your actual key

# Build settings
markdown: kramdown
